apiVersion: v1
kind: worker-app
metadata:
   name: worker-app
   labels:
   app: worker-app
   type: frontend
spec: 
   containers:
      - name: worker-app-container
        image: vsiraparapu/worker-app
